#!/usr/bin/env bash
#==========================================================================
# Initial author of this file: Martin.Vahi@softf1.com
# This file is in public domain.
# The following line is a spdx.org license label line:
# SPDX-License-Identifier: 0BSD
#==========================================================================
chmod -f -R 0700 $HOME/.ssh # is important or things won't work as expected
S_SSH_PRIVATE_KEY_AT_CLIENT_SIDE="$HOME/.ssh/a_private_key_of_the_generated_keypair.txt"
# For the public key of the key pair at SSH server side:
#     cat ./the_public_key.txt >> $HOME/.ssh/authorized_keys
#     chmod -f -R 0700 $HOME/.ssh
# SSH keypairs can be generated by executing:
#     ssh-keygen -t rsa -C "Some Useful Comment" -f ./this_is_key_Foo.txt
#     # and the public key will have file  name     ./this_is_key_Foo.txt.pub
# Also, at SSH server side /etc/ssh/sshd_config the logging in has to be
# explicitly allowed like
#     AllowUsers someuser@192.168.*.*  scoobydoo@192.168.*.*
#     # the IP-address and/or parts of it are about SSH client computer, where 
#     # the user is allowed to log in from.
# and the server side SSH port must be open from 
# SSH server side operating system firewall point of view.
#
S_FP_A_FOLDER_01="$HOME/.ssh/something_for_SSH_connection_reuse"
S_SSHFS_OPTIONS_PART_0=" -o reconnect,ServerAliveInterval=29,ServerAliveCountMax=10,ControlPersist=11,ControlMaster=auto,ControlPath=$S_FP_A_FOLDER_01/%h_%p_%r,follow_symlinks,IdentityFile=$HOME/.ssh/$S_SSH_PRIVATE_KEY_AT_CLIENT_SIDE "
# The "follow_symlinks" at the previous line allows to mount 
# a Raspberry_Pi like computer's user home folder, which 
# probably/most_often resides at a flimsy Flash based memory card, 
# and then use a magnetic USB-harddisk that is connected to the
# Raspberry_Pi by just creating a symlink that leads from 
# /home/somepiuser/the_symlink  --> /path/where/the/usbharddisk/has/been/mounted/outside/of/the/home/somepiuser

S_FP_MOUNTING_FOLDER_AT_SSH_CLIENT_SIDE="$HOME/some/folder/foo"
S_SSH_SERVER_PORT_AT_SERVER_SIDE="22"
S_OPERATING_SYSTEM_USER_AT_SSH_SERVER_SIDE="scoobydoo"
S_SSH_SERVER_IP_ADDRESS="192.168.99.99" # or a domain like ourfuncompanyisveryserious.com
alias mount_remote_home_folder_over_ssh="sshfs -oport=$S_SSH_SERVER_PORT_AT_SERVER_SIDE $S_OPERATING_SYSTEM_USER_AT_SSH_SERVER_SIDE@$S_SSH_SERVER_IP_ADDRESS:/home/$S_OPERATING_SYSTEM_USER_AT_SSH_SERVER_SIDE/ $S_FP_MOUNTING_FOLDER_AT_SSH_CLIENT_SIDE $S_SSHFS_OPTIONS_PART_0 "
alias this_is_the_unmounting_Bash_alias="sudo fusermount -u $S_FP_MOUNTING_FOLDER_AT_SSH_CLIENT_SIDE "
# which would be without the "sudo" on non-WSL Linux.
# An example of the SSH client side "$HOME/.ssh/config":
#     #------citation---start--------
#     Host some_fun_connectionalias_Goooo
#         #IdentitiesOnly yes
#         IdentitiesOnly no
#         IdentityFile ~/.ssh/the_private_key_Foo.txt
#         #PubkeyAuthentication=yes
#         PubkeyAuthentication=no
#         HostName ourfuncompanyisveryserious.com
#         Port 22
#         User scoobydoo
#         ServerAliveInterval 32760
#         ServerAliveCountMax 400
#         #
#         ControlPersist 11
#         # Default unit: seconds.
#         #
#         ControlMaster auto
#         #
#         # %r --- username at the server
#         # %h --- hostname of the server
#         # %p --- port at server
#         # %i --- key ID
#         # %s --- serial number of the key
#         ControlPath  ~/.ssh/something_for_SSH_connection_reuse/%h_%p_%r
# #------citation---end----------
# The above "$HOME/.ssh/config" allows to connect to the ourfuncompanyisveryserious.com
# by running a Bash command:
#     ssh some_fun_connectionalias_Goooo
# A more elaborate example of the "$HOME/.ssh/config" MIGHT reside at 
# https://github.com/martinvahi/mmmv_userspace_distro_t1/blob/75e88b6bf208ec8b8884d0e70750d5eade84e982/home_folder_of_user_named_mmmv/mmmv_userspace_distro_t1/mmmv/lib/templates/_ssh_config_template.txt#L2
# A Bash script template for creating SSH tunnels MIGHT be available at:
# https://github.com/martinvahi/mmmv_userspace_distro_t1/blob/75e88b6bf208ec8b8884d0e70750d5eade84e982/home_folder_of_user_named_mmmv/mmmv_userspace_distro_t1/mmmv/lib/templates/ssh_tunnel_t1.bash#L1
#==========================================================================
# S_VERSION_OF_THIS_FILE="5e34df65-5f4e-448f-8326-e2b3409069e7"
#==========================================================================
