#!/usr/bin/env bash
#==========================================================================
# Author of this file: <INCOMPLETE: name of the author comes here>
# Author of the template of this file: Martin.Vahi@softf1.com
# This file is in public domain.
#
# The following line is a spdx.org license label line:
# SPDX-License-Identifier: 0BSD
#==========================================================================
if [ "$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1" != "mode_ok_to_load" ]; then
    S_ERR_CODE="1"
    echo ""
    echo "This script is expected to be a sub-part of the "
    if [ "$MMMV_USERSPACE_DISTRO_T1_HOME" != "" ]; then
        echo "$MMMV_USERSPACE_DISTRO_T1_HOME/mmmv/etc/common_bashrc/common_bashrc_main.bash"
    else
        echo "\$MMMV_USERSPACE_DISTRO_T1_HOME/mmmv/etc/common_bashrc/common_bashrc_main.bash"
    fi
    if [ "$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1" != "" ]; then
        echo ""
        echo "    MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1==$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1"
        echo ""
    fi
    echo -e "\e[31mExiting with an error code $S_ERR_CODE . \e[39m"
    echo "GUID=='51ccf5cc-9cd3-4651-934a-4261c0309ae7'"
    echo ""
    exit $S_ERR_CODE # exit with an error
fi
#--------------------------------------------------------------------------
if [ "$HOSTNAME" == "BLANKFORHOSTNAME" ]; then
    #----------------------------------------------------------------------
    # S_FP_BASHFILE="/some/custom/foo.bash"
    # SB_OK_4_THE_BASHFILE_2_BE_MISSING_OPTIONAL="f" # domain: {"","t","f"}
    # func_mmmv_include_bashfile_if_possible_t2 "$S_FP_BASHFILE" \
    #     "01510a6c-f3fb-4d15-935a-4261c0309ae7" "$SB_OK_4_THE_BASHFILE_2_BE_MISSING_OPTIONAL"
    #----------------------------------------------------------------------
    # if [ "$SB_LP_EXISTS_ON_PATH" == "t" ]; then
    #     S_TMP_PRINTERNAME="Martini_OKI_ML5520_maatriksprinter"
    #     alias mmmv_print_OKI_ML5520_maatriksprinter="lp -d $S_TMP_PRINTERNAME " # <name of the file comes here>
    # fi
    #----------------------------------------------------------------------
    if [ "$S_WHOAMI" == "" ]; then
        S_WHOAMI="`whoami`"
    fi
    #----------------------------------------------------------------------
    if [ "$SB_OPERATINGSYSTEM_LINUX_WSL" == "f" ]; then
        if [ "$SB_OPERATINGSYSTEM_LINUX_ANDROID" == "f" ]; then
            if [ "$SB_OPERATINGSYSTEM_LINUX_ANDROID_TERMUX" == "f" ]; then
                #----------------------------------------------------------
                if [ "$SB_SETXKBMAP_EXISTS_ON_PATH" == "t" ]; then
                    # At least on some Linux distributions the
                    setxkbmap -layout us,ee -option "grp:ctrl_shift_toggle"
                    # makes Ctrl-Shift to toggle between 2 keybard layouts.
                    # The version for AltGr is:
                    #     setxkbmap -layout us,ee -option "grp:toggle"
                fi
                #----------------------------------------------------------
                if [ "$SB_XSET_EXISTS_ON_PATH" == "t" ]; then
                    # Sets the X11 built in screensaver
                    SI_NUMBER_OF_IDLING_SECONDS_TILL_SCREENSAVER_ACTIVATES="3600"
                    SI_SCREENSAVER_CYCLE_COUNT_BEFORE_LOCKING_SCREEN="0"
                    xset s \
                        $SI_NUMBER_OF_IDLING_SECONDS_TILL_SCREENSAVER_ACTIVATES \
                        $SI_SCREENSAVER_CYCLE_COUNT_BEFORE_LOCKING_SCREEN
                    # Existing values can be displayed by executing:
                    #     xset q
                fi
                #----------------------------------------------------------
                # if [ "$SB_XSSLOCK_EXISTS_ON_PATH" == "t" ]; then
                #     # A comment from i3 window manager autogenerated config file:
                #     # "xss-lock grabs a logind suspend inhibit lock and
                #     # will use i3lock to lock the screen before suspend."
                #     # xss-lock --transfer-sleep-lock -- i3lock --nofork
                #     # The above line has been outcommented, because for some
                #     # reason it takes horribly long time to complete.
                #     # A command for locking the session:
                #     #     loginctl lock-session
                # fi
                #----------------------------------------------------------
                wait ;
                #----------------------------------------------------------
            fi
        fi
    fi
    #----------------------------------------------------------------------
    # if [ "$MMMV_USERSPACE_DISTRO_T1_FP_FLAGFILES_FOR_ALL_USERS" != "" ]; then
    #     if [ -e "$MMMV_USERSPACE_DISTRO_T1_FP_FLAGFILES_FOR_ALL_USERS" ]; then
    #         if [ -d "$MMMV_USERSPACE_DISTRO_T1_FP_FLAGFILES_FOR_ALL_USERS" ]; then
    #         # else clause not needed, because checks are elsewhere
    #         fi
    #     # else clause not needed, because checks are elsewhere
    #     fi
    # fi
    #----------------------------------------------------------------------
    if [ "$S_TIMESTAMP" != "" ]; then
        MMMV_USERSPACE_DISTRO_T1_HOSTNAME_SPECIFIC_INITIALISATIONS_TIMESTAMP="$S_TIMESTAMP"
    else
        if [ "$SB_DISPLAY_VERIFICATION_FAILURE_MESSAGE_DEFAULT" == "t" ]; then
            echo ""
            echo -e "\e[31mSubpart of $HOME/.bashrc is flawed\e[39m."
            echo -e "The S_TIMESTAMP has not been initialized."
            echo "GUID=='d0f438ca-43aa-44e6-be1a-4261c0309ae7'"
            echo ""
        fi
    fi
    #----------------------------------------------------------------------
fi
#==========================================================================
# S_VERSION_OF_THIS_FILE="2579eed1-9f01-4630-894a-4261c0309ae7"
#==========================================================================
