#!/usr/bin/env bash
#==========================================================================
# Initial author of this file: Martin.Vahi@softf1.com
# This file is in public domain.
#
# The following line is a spdx.org license label line:
# SPDX-License-Identifier: 0BSD
#
# As exiting from the ~/.bashrc exits the Bash session,
# the ~/.bashrc and its subparts must not call "exit".
# This script and all of the functions defined in it are "exit" free.
#==========================================================================
# Example code for inclusion to the ~/.bashrc
#
#     S_FP_0="$HOME/<path to this script here>"
#     if [ -e "$S_FP_0" ]; then
#         if [ -d "$S_FP_0" ]; then
#             echo ""
#             echo "A folder with the path of "
#             echo ""
#             echo "    S_FP_0==$S_FP_0"
#             echo ""
#             echo "exists, but a file is expected."
#             echo "GUID=='5f8eb9d5-c71c-45de-9753-b2d2405179e7'"
#             echo ""
#         else
#             source "$S_FP_0"
#         fi
#     else
#         echo ""
#         echo "~/.bashrc sub-part with the path of "
#         echo ""
#         echo "    S_FP_0==$S_FP_0"
#         echo ""
#         echo "could not be found."
#         echo "GUID=='5433acb3-705c-4ab8-b813-b2d2405179e7'"
#         echo ""
#     fi
#
#--------------------------------------------------------------------------

func_mmmv_bashrc_subpart_wget_t1_error_message_t1(){
    local S_GUID_CANDIDATE=$1 # first  function argument
    #----------------------------------------------------------------------
    local SB_THIS_FUNCTION_IS_MISUSED="f"
    if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
        SB_THIS_FUNCTION_IS_MISUSED="t"
    else
        if [ "$SB_WGET_EXISTS_ON_PATH" == "f" ]; then
            SB_THIS_FUNCTION_IS_MISUSED="t"
        fi
    fi
    #----------------------------------------------------------------------
    if [ "$SB_THIS_FUNCTION_IS_MISUSED" == "f" ]; then
        echo ""
        echo -e "\e[31mThe ~/.bashrc or at least one of its sub-parts has a flaw.\e[39m"
        echo "A valid domain for the SB_WGET_EXISTS_ON_PATH is {"t","f"}, but "
        echo ""
        echo "    SB_WGET_EXISTS_ON_PATH==\"$SB_WGET_EXISTS_ON_PATH\""
        echo ""
        if [ "$S_GUID_CANDIDATE" != "" ]; then
            echo "S_GUID_CANDIDATE=='$S_GUID_CANDIDATE'"
        fi
        echo "GUID=='56dbc771-2277-4a0b-b323-b2d2405179e7'"
        echo ""
    else
        echo ""
        if [ "$SB_THIS_FUNCTION_IS_MISUSED" == "t" ]; then
            echo -e "\e[31mThis function is misused.\e[39m"
        else
            echo -e "\e[31mThis function is flawed.\e[39m"
        fi
        if [ "$S_GUID_CANDIDATE" != "" ]; then
            echo "S_GUID_CANDIDATE=='$S_GUID_CANDIDATE'"
        fi
        echo "GUID=='a467698d-8366-4279-8cb3-b2d2405179e7'"
        echo ""
    fi
    #----------------------------------------------------------------------
    # exit 1 # must NOT be called in ~/.bashrc, because
             # exiting from the ~/.bashrc exits the session.
    #----------------------------------------------------------------------
} # func_mmmv_bashrc_subpart_wget_t1_error_message_t1

#--------------------------------------------------------------------------
if [ "$SB_WGET_EXISTS_ON_PATH" == "" ]; then
    SB_WGET_EXISTS_ON_PATH="f"
    S_FP_WGET="`which wget 2> /dev/null`"
    if [ "$S_FP_WGET" != "" ]; then
        SB_WGET_EXISTS_ON_PATH="t"
    # else
    # # Outcommented here, buecause the test resides elsewhere
    # # and the test here would duplicate error messages.
    #     func_mmmv_userspace_distro_t1_err_msg_console_program_missing_t1 \
    #         "curl" "e4e55cdb-6ede-49fb-9813-b2d2405179e7"
    fi
else
    if [ "$SB_WGET_EXISTS_ON_PATH" != "t" ]; then
        if [ "$SB_WGET_EXISTS_ON_PATH" != "f" ]; then
            func_mmmv_bashrc_subpart_wget_t1_error_message_t1 \
                "52bcadc1-75de-414a-b623-b2d2405179e7"
        fi
    fi
fi
if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
    if [ "$S_FP_WGET" == "" ]; then
        S_FP_WGET="`which wget 2> /dev/null`"
    fi
fi
#--------------------------------------------------------------------------
if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
    MMMV_WGET_RECURSIVE_PART_NICE="$S_FP_NICE -n 15 "
    alias mmmv_wget_ignore_https_cert_t1="$MMMV_WGET_RECURSIVE_PART_NICE $S_FP_WGET --no-check-certificate "
else
    if [ "$SB_WGET_EXISTS_ON_PATH" != "f" ]; then
        func_mmmv_bashrc_subpart_wget_t1_error_message_t1 \
            "a26281f3-b8a3-414e-ae53-b2d2405179e7"
    fi
fi
#--------------------------------------------------------------------------
# if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
#     #----------------------------------------------------------------------
#     MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET=" \
#     $S_FP_WGET --recursive --convert-links --adjust-extension --page-requisites \
#     --tries=3 --waitretry=2  --timeout=10 --user-agent=firefox "
#     # -e robots=off --no-check-certificate "
#     #----------------------------------------------------------------------
#     MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD=" \
#     $MMMV_WGET_RECURSIVE_PART_NICE \
#     $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET "
#     #--------
#     MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS=" \
#     $MMMV_WGET_RECURSIVE_PART_NICE \
#     torsocks \
#     $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET "
#     #--------
#     MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT=" \
#     $MMMV_WGET_RECURSIVE_PART_NICE \
#     $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET -e robots=off "
#     #--------
#     MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT=" \
#     $MMMV_WGET_RECURSIVE_PART_NICE \
#     torsocks \
#     $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET -e robots=off "
#     #----------------------------------------------------------------------
#     MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD -H "
#     #--------
#     MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT="\
#     #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD -H -e robots=off "
#     #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT -H "
#     #--------
#     MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS -H "
#     #--------
#     MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT="\
#     #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS -H -e robots=off "
#     #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT -H "
#     #----------------------------------------------------------------------
#     alias mmmv_wget_recursive_single_domain_1="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=1 "
#     alias mmmv_wget_recursive_single_domain_2="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=2 "
#     alias mmmv_wget_recursive_single_domain_3="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=3 "
#     alias mmmv_wget_recursive_single_domain_4="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=4 "
#     alias mmmv_wget_recursive_single_domain_5="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=5 "
#     alias mmmv_wget_recursive_single_domain_6="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=6 "
#     alias mmmv_wget_recursive_single_domain_7="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=7 "
#     alias mmmv_wget_recursive_single_domain_8="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=8 "
#     alias mmmv_wget_recursive_single_domain_9="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=9 "
#     alias mmmv_wget_recursive_single_domain_10="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD --level=10 "
#     #--------
#     alias mmmv_wget_recursive_across_domains_1="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=1 "
#     alias mmmv_wget_recursive_across_domains_2="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=2 "
#     alias mmmv_wget_recursive_across_domains_3="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=3 "
#     alias mmmv_wget_recursive_across_domains_4="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=4 "
#     alias mmmv_wget_recursive_across_domains_5="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=5 "
#     alias mmmv_wget_recursive_across_domains_6="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=6 "
#     alias mmmv_wget_recursive_across_domains_7="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=7 "
#     alias mmmv_wget_recursive_across_domains_8="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=8 "
#     alias mmmv_wget_recursive_across_domains_9="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=9 "
#     alias mmmv_wget_recursive_across_domains_10="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET --level=10 "
#     #----------------------------------------------------------------------
#     # Start of robots.txt ignorance.
#     alias mmmv_wget_recursive_single_domain_1_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=1 "
#     alias mmmv_wget_recursive_single_domain_2_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=2 "
#     alias mmmv_wget_recursive_single_domain_3_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=3 "
#     alias mmmv_wget_recursive_single_domain_4_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=4 "
#     alias mmmv_wget_recursive_single_domain_5_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=5 "
#     alias mmmv_wget_recursive_single_domain_6_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=6 "
#     alias mmmv_wget_recursive_single_domain_7_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=7 "
#     alias mmmv_wget_recursive_single_domain_8_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=8 "
#     alias mmmv_wget_recursive_single_domain_9_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=9 "
#     alias mmmv_wget_recursive_single_domain_10_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT --level=10 "
#     #--------
#     alias mmmv_wget_recursive_across_domains_1_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=1 "
#     alias mmmv_wget_recursive_across_domains_2_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=2 "
#     alias mmmv_wget_recursive_across_domains_3_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=3 "
#     alias mmmv_wget_recursive_across_domains_4_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=4 "
#     alias mmmv_wget_recursive_across_domains_5_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=5 "
#     alias mmmv_wget_recursive_across_domains_6_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=6 "
#     alias mmmv_wget_recursive_across_domains_7_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=7 "
#     alias mmmv_wget_recursive_across_domains_8_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=8 "
#     alias mmmv_wget_recursive_across_domains_9_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=9 "
#     alias mmmv_wget_recursive_across_domains_10_ignore_robots_txt="\
#         $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT --level=10 "
#     # End of robots.txt ignorance.
#     #----------------------------------------------------------------------
#     #if [ "`which torsocks`" != "" ]; then # a lot of command line output if torsocks missing from PATH
#     if [ "$SB_TORSOCKS_EXISTS_ON_PATH" == "t" ]; then
#         alias mmmv_wget_recursive_single_domain_1_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=1 "
#         alias mmmv_wget_recursive_single_domain_2_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=2 "
#         alias mmmv_wget_recursive_single_domain_3_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=3 "
#         alias mmmv_wget_recursive_single_domain_4_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=4 "
#         alias mmmv_wget_recursive_single_domain_5_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=5 "
#         alias mmmv_wget_recursive_single_domain_6_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=6 "
#         alias mmmv_wget_recursive_single_domain_7_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=7 "
#         alias mmmv_wget_recursive_single_domain_8_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=8 "
#         alias mmmv_wget_recursive_single_domain_9_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=9 "
#         alias mmmv_wget_recursive_single_domain_10_torsocks="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS --level=10 "
#         #--------
#         alias mmmv_wget_recursive_across_domains_1_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=1 "
#         alias mmmv_wget_recursive_across_domains_2_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=2 "
#         alias mmmv_wget_recursive_across_domains_3_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=3 "
#         alias mmmv_wget_recursive_across_domains_4_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=4 "
#         alias mmmv_wget_recursive_across_domains_5_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=5 "
#         alias mmmv_wget_recursive_across_domains_6_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=6 "
#         alias mmmv_wget_recursive_across_domains_7_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=7 "
#         alias mmmv_wget_recursive_across_domains_8_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=8 "
#         alias mmmv_wget_recursive_across_domains_9_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=9 "
#         alias mmmv_wget_recursive_across_domains_10_torsocks="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS --level=10 "
#         #------------------------------------------------------------------
#         # Start of robots.txt ignorance.
#         alias mmmv_wget_recursive_single_domain_1_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=1 "
#         alias mmmv_wget_recursive_single_domain_2_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=2 "
#         alias mmmv_wget_recursive_single_domain_3_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=3 "
#         alias mmmv_wget_recursive_single_domain_4_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=4 "
#         alias mmmv_wget_recursive_single_domain_5_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=5 "
#         alias mmmv_wget_recursive_single_domain_6_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=6 "
#         alias mmmv_wget_recursive_single_domain_7_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=7 "
#         alias mmmv_wget_recursive_single_domain_8_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=8 "
#         alias mmmv_wget_recursive_single_domain_9_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=9 "
#         alias mmmv_wget_recursive_single_domain_10_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=10 "
#         #--------
#         alias mmmv_wget_recursive_across_domains_1_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=1 "
#         alias mmmv_wget_recursive_across_domains_2_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=2 "
#         alias mmmv_wget_recursive_across_domains_3_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=3 "
#         alias mmmv_wget_recursive_across_domains_4_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=4 "
#         alias mmmv_wget_recursive_across_domains_5_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=5 "
#         alias mmmv_wget_recursive_across_domains_6_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=6 "
#         alias mmmv_wget_recursive_across_domains_7_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=7 "
#         alias mmmv_wget_recursive_across_domains_8_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=8 "
#         alias mmmv_wget_recursive_across_domains_9_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=9 "
#         alias mmmv_wget_recursive_across_domains_10_torsocks_ignore_robots_txt="\
#             $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT --level=10 "
#         # End of robots.txt ignorance.
#         #------------------------------------------------------------------
#     fi
#     #----------------------------------------------------------------------
# else
#     if [ "$SB_WGET_EXISTS_ON_PATH" != "f" ]; then
#         func_mmmv_bashrc_subpart_wget_t1_error_message_t1 \
#             "43513712-039f-4a15-a712-b2d2405179e7"
#     fi
# fi
#
#--------------------------------------------------------------------------
if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_2_10=" \
    $S_FP_WGET --recursive --convert-links --adjust-extension --page-requisites \
    --tries=3 --waitretry=2  --timeout=10 --user-agent=firefox "
    # -e robots=off --no-check-certificate "
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_2_10 "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    torsocks \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_2_10 "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_2_10 -e robots=off "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    torsocks \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_2_10 -e robots=off "
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 -H -e robots=off "
    #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 -H -e robots=off "
    #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 -H "
    #----------------------------------------------------------------------
    alias mmmv_wget_recursive_single_domain_1_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=1 "
    alias mmmv_wget_recursive_single_domain_2_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=2 "
    alias mmmv_wget_recursive_single_domain_3_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=3 "
    alias mmmv_wget_recursive_single_domain_4_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=4 "
    alias mmmv_wget_recursive_single_domain_5_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=5 "
    alias mmmv_wget_recursive_single_domain_6_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=6 "
    alias mmmv_wget_recursive_single_domain_7_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=7 "
    alias mmmv_wget_recursive_single_domain_8_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=8 "
    alias mmmv_wget_recursive_single_domain_9_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=9 "
    alias mmmv_wget_recursive_single_domain_10_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_2_10 --level=10 "
    #--------
    alias mmmv_wget_recursive_across_domains_1_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=1 "
    alias mmmv_wget_recursive_across_domains_2_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=2 "
    alias mmmv_wget_recursive_across_domains_3_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=3 "
    alias mmmv_wget_recursive_across_domains_4_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=4 "
    alias mmmv_wget_recursive_across_domains_5_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=5 "
    alias mmmv_wget_recursive_across_domains_6_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=6 "
    alias mmmv_wget_recursive_across_domains_7_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=7 "
    alias mmmv_wget_recursive_across_domains_8_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=8 "
    alias mmmv_wget_recursive_across_domains_9_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=9 "
    alias mmmv_wget_recursive_across_domains_10_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_2_10 --level=10 "
    #----------------------------------------------------------------------
    # Start of robots.txt ignorance.
    alias mmmv_wget_recursive_single_domain_1_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=1 "
    alias mmmv_wget_recursive_single_domain_2_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=2 "
    alias mmmv_wget_recursive_single_domain_3_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=3 "
    alias mmmv_wget_recursive_single_domain_4_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=4 "
    alias mmmv_wget_recursive_single_domain_5_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=5 "
    alias mmmv_wget_recursive_single_domain_6_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=6 "
    alias mmmv_wget_recursive_single_domain_7_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=7 "
    alias mmmv_wget_recursive_single_domain_8_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=8 "
    alias mmmv_wget_recursive_single_domain_9_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=9 "
    alias mmmv_wget_recursive_single_domain_10_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_2_10 --level=10 "
    #--------
    alias mmmv_wget_recursive_across_domains_1_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=1 "
    alias mmmv_wget_recursive_across_domains_2_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=2 "
    alias mmmv_wget_recursive_across_domains_3_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=3 "
    alias mmmv_wget_recursive_across_domains_4_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=4 "
    alias mmmv_wget_recursive_across_domains_5_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=5 "
    alias mmmv_wget_recursive_across_domains_6_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=6 "
    alias mmmv_wget_recursive_across_domains_7_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=7 "
    alias mmmv_wget_recursive_across_domains_8_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=8 "
    alias mmmv_wget_recursive_across_domains_9_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=9 "
    alias mmmv_wget_recursive_across_domains_10_ignore_robots_txt_t_3_2_10="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_2_10 --level=10 "
    # End of robots.txt ignorance.
    #----------------------------------------------------------------------
    #if [ "`which torsocks`" != "" ]; then # a lot of command line output if torsocks missing from PATH
    if [ "$SB_TORSOCKS_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_wget_recursive_single_domain_1_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=1 "
        alias mmmv_wget_recursive_single_domain_2_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=2 "
        alias mmmv_wget_recursive_single_domain_3_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=3 "
        alias mmmv_wget_recursive_single_domain_4_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=4 "
        alias mmmv_wget_recursive_single_domain_5_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=5 "
        alias mmmv_wget_recursive_single_domain_6_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=6 "
        alias mmmv_wget_recursive_single_domain_7_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=7 "
        alias mmmv_wget_recursive_single_domain_8_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=8 "
        alias mmmv_wget_recursive_single_domain_9_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=9 "
        alias mmmv_wget_recursive_single_domain_10_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_2_10 --level=10 "
        #--------
        alias mmmv_wget_recursive_across_domains_1_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=1 "
        alias mmmv_wget_recursive_across_domains_2_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=2 "
        alias mmmv_wget_recursive_across_domains_3_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=3 "
        alias mmmv_wget_recursive_across_domains_4_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=4 "
        alias mmmv_wget_recursive_across_domains_5_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=5 "
        alias mmmv_wget_recursive_across_domains_6_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=6 "
        alias mmmv_wget_recursive_across_domains_7_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=7 "
        alias mmmv_wget_recursive_across_domains_8_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=8 "
        alias mmmv_wget_recursive_across_domains_9_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=9 "
        alias mmmv_wget_recursive_across_domains_10_torsocks_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_2_10 --level=10 "
        #------------------------------------------------------------------
        # Start of robots.txt ignorance.
        alias mmmv_wget_recursive_single_domain_1_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=1 "
        alias mmmv_wget_recursive_single_domain_2_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=2 "
        alias mmmv_wget_recursive_single_domain_3_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=3 "
        alias mmmv_wget_recursive_single_domain_4_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=4 "
        alias mmmv_wget_recursive_single_domain_5_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=5 "
        alias mmmv_wget_recursive_single_domain_6_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=6 "
        alias mmmv_wget_recursive_single_domain_7_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=7 "
        alias mmmv_wget_recursive_single_domain_8_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=8 "
        alias mmmv_wget_recursive_single_domain_9_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=9 "
        alias mmmv_wget_recursive_single_domain_10_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=10 "
        #--------
        alias mmmv_wget_recursive_across_domains_1_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=1 "
        alias mmmv_wget_recursive_across_domains_2_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=2 "
        alias mmmv_wget_recursive_across_domains_3_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=3 "
        alias mmmv_wget_recursive_across_domains_4_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=4 "
        alias mmmv_wget_recursive_across_domains_5_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=5 "
        alias mmmv_wget_recursive_across_domains_6_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=6 "
        alias mmmv_wget_recursive_across_domains_7_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=7 "
        alias mmmv_wget_recursive_across_domains_8_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=8 "
        alias mmmv_wget_recursive_across_domains_9_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=9 "
        alias mmmv_wget_recursive_across_domains_10_torsocks_ignore_robots_txt_t_3_2_10="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_2_10 --level=10 "
        # End of robots.txt ignorance.
        #------------------------------------------------------------------
    fi
    #----------------------------------------------------------------------
else
    if [ "$SB_WGET_EXISTS_ON_PATH" != "f" ]; then
        func_mmmv_bashrc_subpart_wget_t1_error_message_t1 \
            "1d0ed2b4-acd4-42c3-9252-b2d2405179e7"
    fi
fi

#--------------------------------------------------------------------------
if [ "$SB_WGET_EXISTS_ON_PATH" == "t" ]; then
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_4_60=" \
    $S_FP_WGET --recursive --convert-links --adjust-extension --page-requisites \
    --tries=3 --waitretry=4  --timeout=60 --user-agent=firefox "
    # -e robots=off --no-check-certificate "
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_4_60 "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    torsocks \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_4_60 "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_4_60 -e robots=off "
    #--------
    MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60=" \
    $MMMV_WGET_RECURSIVE_PART_NICE \
    torsocks \
    $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_PART_WGET_3_4_60 -e robots=off "
    #----------------------------------------------------------------------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 -H -e robots=off "
    #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 -H "
    #--------
    MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 -H -e robots=off "
    #   $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 -H "
    #----------------------------------------------------------------------
    alias mmmv_wget_recursive_single_domain_1_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=1 "
    alias mmmv_wget_recursive_single_domain_2_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=2 "
    alias mmmv_wget_recursive_single_domain_3_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=3 "
    alias mmmv_wget_recursive_single_domain_4_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=4 "
    alias mmmv_wget_recursive_single_domain_5_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=5 "
    alias mmmv_wget_recursive_single_domain_6_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=6 "
    alias mmmv_wget_recursive_single_domain_7_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=7 "
    alias mmmv_wget_recursive_single_domain_8_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=8 "
    alias mmmv_wget_recursive_single_domain_9_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=9 "
    alias mmmv_wget_recursive_single_domain_10_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_3_4_60 --level=10 "
    #--------
    alias mmmv_wget_recursive_across_domains_1_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=1 "
    alias mmmv_wget_recursive_across_domains_2_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=2 "
    alias mmmv_wget_recursive_across_domains_3_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=3 "
    alias mmmv_wget_recursive_across_domains_4_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=4 "
    alias mmmv_wget_recursive_across_domains_5_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=5 "
    alias mmmv_wget_recursive_across_domains_6_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=6 "
    alias mmmv_wget_recursive_across_domains_7_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=7 "
    alias mmmv_wget_recursive_across_domains_8_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=8 "
    alias mmmv_wget_recursive_across_domains_9_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=9 "
    alias mmmv_wget_recursive_across_domains_10_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_3_4_60 --level=10 "
    #----------------------------------------------------------------------
    # Start of robots.txt ignorance.
    alias mmmv_wget_recursive_single_domain_1_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=1 "
    alias mmmv_wget_recursive_single_domain_2_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=2 "
    alias mmmv_wget_recursive_single_domain_3_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=3 "
    alias mmmv_wget_recursive_single_domain_4_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=4 "
    alias mmmv_wget_recursive_single_domain_5_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=5 "
    alias mmmv_wget_recursive_single_domain_6_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=6 "
    alias mmmv_wget_recursive_single_domain_7_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=7 "
    alias mmmv_wget_recursive_single_domain_8_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=8 "
    alias mmmv_wget_recursive_single_domain_9_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=9 "
    alias mmmv_wget_recursive_single_domain_10_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_IGNORE_ROBOTS_TXT_3_4_60 --level=10 "
    #--------
    alias mmmv_wget_recursive_across_domains_1_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=1 "
    alias mmmv_wget_recursive_across_domains_2_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=2 "
    alias mmmv_wget_recursive_across_domains_3_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=3 "
    alias mmmv_wget_recursive_across_domains_4_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=4 "
    alias mmmv_wget_recursive_across_domains_5_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=5 "
    alias mmmv_wget_recursive_across_domains_6_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=6 "
    alias mmmv_wget_recursive_across_domains_7_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=7 "
    alias mmmv_wget_recursive_across_domains_8_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=8 "
    alias mmmv_wget_recursive_across_domains_9_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=9 "
    alias mmmv_wget_recursive_across_domains_10_ignore_robots_txt_t_3_4_60="\
        $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_WGET_IGNORE_ROBOTS_TXT_3_4_60 --level=10 "
    # End of robots.txt ignorance.
    #----------------------------------------------------------------------
    #if [ "`which torsocks`" != "" ]; then # a lot of command line output if torsocks missing from PATH
    if [ "$SB_TORSOCKS_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_wget_recursive_single_domain_1_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=1 "
        alias mmmv_wget_recursive_single_domain_2_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=2 "
        alias mmmv_wget_recursive_single_domain_3_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=3 "
        alias mmmv_wget_recursive_single_domain_4_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=4 "
        alias mmmv_wget_recursive_single_domain_5_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=5 "
        alias mmmv_wget_recursive_single_domain_6_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=6 "
        alias mmmv_wget_recursive_single_domain_7_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=7 "
        alias mmmv_wget_recursive_single_domain_8_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=8 "
        alias mmmv_wget_recursive_single_domain_9_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=9 "
        alias mmmv_wget_recursive_single_domain_10_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_3_4_60 --level=10 "
        #--------
        alias mmmv_wget_recursive_across_domains_1_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=1 "
        alias mmmv_wget_recursive_across_domains_2_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=2 "
        alias mmmv_wget_recursive_across_domains_3_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=3 "
        alias mmmv_wget_recursive_across_domains_4_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=4 "
        alias mmmv_wget_recursive_across_domains_5_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=5 "
        alias mmmv_wget_recursive_across_domains_6_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=6 "
        alias mmmv_wget_recursive_across_domains_7_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=7 "
        alias mmmv_wget_recursive_across_domains_8_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=8 "
        alias mmmv_wget_recursive_across_domains_9_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=9 "
        alias mmmv_wget_recursive_across_domains_10_torsocks_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_3_4_60 --level=10 "
        #------------------------------------------------------------------
        # Start of robots.txt ignorance.
        alias mmmv_wget_recursive_single_domain_1_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=1 "
        alias mmmv_wget_recursive_single_domain_2_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=2 "
        alias mmmv_wget_recursive_single_domain_3_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=3 "
        alias mmmv_wget_recursive_single_domain_4_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=4 "
        alias mmmv_wget_recursive_single_domain_5_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=5 "
        alias mmmv_wget_recursive_single_domain_6_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=6 "
        alias mmmv_wget_recursive_single_domain_7_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=7 "
        alias mmmv_wget_recursive_single_domain_8_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=8 "
        alias mmmv_wget_recursive_single_domain_9_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=9 "
        alias mmmv_wget_recursive_single_domain_10_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_SINGLE_DOMAIN_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=10 "
        #--------
        alias mmmv_wget_recursive_across_domains_1_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=1 "
        alias mmmv_wget_recursive_across_domains_2_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=2 "
        alias mmmv_wget_recursive_across_domains_3_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=3 "
        alias mmmv_wget_recursive_across_domains_4_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=4 "
        alias mmmv_wget_recursive_across_domains_5_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=5 "
        alias mmmv_wget_recursive_across_domains_6_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=6 "
        alias mmmv_wget_recursive_across_domains_7_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=7 "
        alias mmmv_wget_recursive_across_domains_8_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=8 "
        alias mmmv_wget_recursive_across_domains_9_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=9 "
        alias mmmv_wget_recursive_across_domains_10_torsocks_ignore_robots_txt_t_3_4_60="\
            $MMMV_WGET_RECURSIVE_ACROSS_DOMAINS_CMD_TORSOCKS_IGNORE_ROBOTS_TXT_3_4_60 --level=10 "
        # End of robots.txt ignorance.
        #------------------------------------------------------------------
    fi
    #----------------------------------------------------------------------
else
    if [ "$SB_WGET_EXISTS_ON_PATH" != "f" ]; then
        func_mmmv_bashrc_subpart_wget_t1_error_message_t1 \
            "11b5fcb1-c2f4-46b5-a252-b2d2405179e7"
    fi
fi
#==========================================================================
# S_VERSION_OF_THIS_FILE="14994a24-5856-4902-b332-b2d2405179e7"
#==========================================================================
