#!/usr/bin/env bash
#==========================================================================
# This file is an optional file that will be searched for from 
# the path of 
#
#     $HOME/m_local/etc/_bashrc_optional_extra_00.bash
#
# It must be accompanied by 
#
#     $HOME/m_local/etc/_bashrc_optional_extra_00_bash_subpart_01
#
# which is expected to be customised.
#
#==========================================================================

SB_IS_PRESENT_IN_LIST="f"
func_mmmv_userspace_distro_t1_OK_for_the_program_to_be_missing(){
    local SB_PROGRAM_NAME="$1"
#--------------------------------------------------------------------------
# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=block_ba67a111-de96-478d-8454-83211110b7e7_city
# RENESSAATOR_SOURCE_LANGUAGE=Ruby
# RENESSAATOR_SOURCE_START
# s_fp_this_bash_file=""+ENV["S_FP_RENESSAATOR_BLOCK_ORIGIN"]
# s_fp_this_bash_file_parent_folder=s_fp_this_bash_file.reverse.sub(/^[^\/]+[\/]/,"").reverse
# s_fp_rb=s_fp_this_bash_file_parent_folder+"/_bashrc_optional_extra_00_bash_subpart_01.rb"
# require s_fp_rb
# #puts s_fp_rb
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
#---------------------------------------------------------------------
# As of 2023_11 the Microsoft Bing chat-bot claims that 
# hashtables were introduced to Bash in year 2009 and that   
# the arithmetic for statement is available in Bash since year 1989. 
# This autognerated awful-ness here is a brute force version of a 
# read-only hashtable substitute that might work also with the 1989 
# version of Bash. Thank You for studying this script :-) 
# GUID=='6d5d423c-c180-4d2d-a2e3-6162c0f049e7' 
#---------------------------------------------------------------------
SB_IS_PRESENT_IN_LIST="f"
#---------------------------------------------------------------------

# RENESSAATOR_AUTOGENERATED_TEXT_END
#
# RENESSAATOR_BLOCK_END
    #----------------------------------------------------------------------
} # func_mmmv_userspace_distro_t1_OK_for_the_program_to_be_missing
#==========================================================================
# S_VERSION_OF_THIS_FILE="efc6a41a-73af-4da2-a4e3-6162c0f049e7"
#==========================================================================
