#!/usr/bin/env bash
#==========================================================================
# Author of this file: <INCOMPLETE: name of the author comes here>
# This file is in public domain.
#
# Initial author of the template of this file: Martin.Vahi@softf1.com
# The following line is a spdx.org license label line:
# SPDX-License-Identifier: 0BSD
#==========================================================================
#S_FP_DIR_TMP_0="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 
#if [ "$MMMV_USERSPACE_DISTRO_T1_HOME" == "" ]; then
#    MMMV_USERSPACE_DISTRO_T1_HOME="`cd $S_FP_DIR_TMP_0/../../../../../../; pwd`"
#fi
#--------------------------------------------------------------------------
if [ "$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1" != "mode_ok_to_load" ]; then
    S_ERR_CODE="1"
    echo ""
    echo "This script is expected to be a sub-part of the "
    if [ "$MMMV_USERSPACE_DISTRO_T1_HOME" != "" ]; then
        echo "$MMMV_USERSPACE_DISTRO_T1_HOME/mmmv/etc/common_bashrc/common_bashrc_main.bash"
    else
        echo "\$MMMV_USERSPACE_DISTRO_T1_HOME/mmmv/etc/common_bashrc/common_bashrc_main.bash"
    fi
    if [ "$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1" != "" ]; then
        echo ""
        echo "    MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1==$MMMV_USERSPACE_DISTRO_T1_BASHRC_PREFIX_LOAD_MODE_T1"
        echo ""
    fi
    echo -e "\e[31mExiting with an error code $S_ERR_CODE . \e[39m"
    echo "GUID=='4c1b82fb-7834-493f-b524-7352c0f049e7'"
    echo ""
    exit $S_ERR_CODE # exit with an error
fi
#--------------------------------------------------------------------------
if [ "`whoami`" == "INCOMPLETE_please_update_this_blank_here" ]; then
    #----------------------------------------------------------------------
    S_FP_0="/home/mmmv/applications/declare_applications.bash"
    func_mmmv_userspace_distro_t1_specific_Bash_file_inclusion_t1 "$S_FP_0"
    #----------------------------------------------------------------------
    # S_FP_BASHFILE="/some/custom/foo.bash"
    # SB_OK_4_THE_BASHFILE_2_BE_MISSING_OPTIONAL="f" # domain: {"","t","f"}
    # func_mmmv_include_bashfile_if_possible_t2 "$S_FP_BASHFILE" \
    #     "489f3225-3c58-496f-8324-7352c0f049e7" "$SB_OK_4_THE_BASHFILE_2_BE_MISSING_OPTIONAL"
    #----------------------------------------------------------------------
    # S_TMP_PRINTERNAME="Martini_OKI_ML5520_maatriksprinter"
    # alias mmmv_print_OKI_ML5520_maatriksprinter="lp -d $S_TMP_PRINTERNAME " # name of the file comes here
    #----------------------------------------------------------------------
    S_TMP_0="$HOME/m_local/etc/list_of_vimwikis.txt"
    if [ "$SB_VIM_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_vim_edit_list_of_vimwikis="nice -n 2 vim $S_TMP_0 ; "
    fi
    if [ "$SB_RUBY_EXISTS_ON_PATH" == "t" ]; then
        alias mmmv_admin_update_list_of_vimwikis="mmmv_admin_vimwiki_list_of_wikis_2_vimrc_subpart_t1.rb '--origin=$S_TMP_0'"
    fi
    #----------------------------------------------------------------------
    # S_TMP_0="/home/mmmv/mmmv_userspace_distro_t1/attic/documentation/application_specific_documentation/vimwiki/notes_set_01/in_vimwiki_format/index.wiki"
    # if [ -e "$S_TMP_0" ]; then
    #     if [ ! -d "$S_TMP_0" ]; then
    #         alias mmmv_vimwiki_userspace_distro_t1_notes_set_01="vim $S_TMP_0 "
    #     fi
    # fi
    #----------------------------------------------------------------------
    # S_TMP_0="/home/mmmv/mmmv_userspace_distro_t1/attic/documentation/development_ideas/arendusideede_vimwiki/index.wiki"
    # if [ -e "$S_TMP_0" ]; then
    #     if [ ! -d "$S_TMP_0" ]; then
    #         alias mmmv_vimwiki_userspace_distro_t1_development_ideas="vim $S_TMP_0 "
    #     fi
    # fi
    #----------------------------------------------------------------------
    MMMV_USERSPACE_DISTRO_T1_HOSTNAME_SPECIFIC_INITIALISATIONS_TIMESTAMP="$S_TIMESTAMP"
fi
#==========================================================================
# S_VERSION_OF_THIS_FILE="e3ac07fe-5caa-4403-b124-7352c0f049e7"
#==========================================================================
